version: "3.9"
services:
  telegram-scraper:
    build: .
    container_name: telegram-scraper
    env_file: .env
    volumes:
      - ./data:/app/data
      - ./sessions:/app/sessions
    restart: always
